### ISSUE TITLE
Api & account settings not available ?

### ISSUE THREAD

**Issue by juju4** [tomchop/malcom#16]
Hello,

I'm trying 1.2 alpha and it find very light and visual, especially compare to alternatives :)
My current problem, it seems the api links are not available

$ curl http://127.0.0.1:8080/api/query?value=malcom.io 
This page does not exist

checking webserver.py
$ curl http://127.0.0.1:8080/public/api?value=malcom.io 
[]
$ curl http://127.0.0.1:8080/evil?value=bevrifuli.geohats.com
{"nodes": [], "edges": []}
$ curl http://127.0.0.1:8080/api/analytics
Internal Server Error
= ValueError: View function did not return a response

and grepping account inside source just returns one line
$ grep -rin account *
web/static/jquery/jquery-ui.js:13781:           // into account and update option properly.
= No /account/settings to generate API key

unreleased stuff? or I missed a doc/code ?

Thanks Tom

**Comment by tomchop** [comment]
Getting back to you on this, sorry for the massive delay. Have you tried running the latest version of Malcom? There has been quite a lot of changes and bugfixes. Let me know.

**Comment by juju4** [comment]
Hello Tom,
No problem. I'm currently upgrading my main system (testing Qubes) so probably not during the week, will try this week-end hopefully.
(and congrats for new release stuff :)

**Comment by juju4** [comment]
Still too much to do testing on Qubes. back lubuntu/vagrant

Quick try, but still have the same error with the web module when launching malcom(AttributeError: 'LoginManager' object has no attribute 'request_loader'). other modules one by one or all start without error. test_feeds.py starts and stopped on an 'ordinal not in range'.

I copied default malcom.conf and git clone current.

Also gave a try to docker
$ sudo docker pull tomchop/malcom
Pulling repository tomchop/malcom
fac211dad424: Download complete
[... ends OK]
$ sudo docker run -P -d --name malcom tomchop/malcom
3773510edb6c67c32589575b1c23c411edfa703c9f59860e8ce18f8674af4afc
$ sudo docker port malcom
Usage: docker port CONTAINER PRIVATE_PORT
Lookup the public-facing port which is NAT-ed to PRIVATE_PORT
$ dpkg -l |grep docker.io
ii  docker.io                             1.0.1~dfsg1-0ubuntu1~ubuntu0.14.04.1  amd64        Linux container runtime
(I know, it bit old..)

with a later one (1.5), 'docker port malcom' outputs nothing ...

**Comment by tomchop** [comment]
Are you using the latest Docker version? They recommend not to use the Ubuntu-managed package: https://docs.docker.com/installation/ubuntulinux/#installing-docker-on-ubuntu... that's what I followed for my installs. The `tomchop/malcom` Docker image should work correctly, but you can also try with `tomchop/malcom-automatic` (this one follows the latest commit on GitHub).

At any rate, the error you're getting when launching Malcom manually is still quite strange. I'll re-do the install procedure tonight. If you have time, please check that the requirements in `requirements.txt` are all installed (you can try doing one more `pip install -r requirements.txt` just to be sure).

Thanks for your help!

**Comment by tomchop** [comment]
Well, I just tested the install procedure from scratch on Ubuntu 14.04 and it works just fine. Are you sure you're installing all the packages from `requirements.txt`? Sounds like compatibility issues with `flask-login`. Let me know if I can help you further.

**Comment by juju4** [comment]
That's it ... if I go with upstream 'pip install -r requirements.txt', it works well.
But if I stay with mostly ubuntu14.04 packages, it bugged (probably flask-login, but also had pip bugging me and had to update it too).

Seems there is really lot of nice change in the interface. great work!
