### ISSUE TITLE
Stop the uploading of a pcap.

### ISSUE THREAD

**Issue by eldraco** [tomchop/malcom#17]
It would be nice to have some way of stopping the uploading of a pcap. Sometimes it is too big and you don't want to wait so long. Or maybe it is just too big.

thanks!

**Comment by ashemery** [comment]
First, can't tell you how much your work is helping me! Thank you very much.

Then, I agree with Seba, that such button would be great. If you stop the upload from the browser, you might end up of killing the whole session and getting a session with no packets or corrupted session. The solution would be to remove them directly from the Mongodb. At least this is what I did.

Thanks again Tom.

**Comment by tomchop** [comment]
Thanks for the tip. It's been a while since Malcom had some love, but I will be revisiting the project soon and taking this into account.
