### ISSUE TITLE
Change the way elements are associated to a sniffing session

### ISSUE THREAD

**Issue by tomchop** [tomchop/malcom#33]
Elements are associated to a sniffing session via tags: the name of a sniffing session will be added as a tag to the element. This is not flexible.

Enhancement: add a new field to the element containing an array to all sniffing session IDs it is present in. When a sniffing session is created and an element is added to the database from this sniffing session, it will add its own ID to the array.

**Comment by sebdraven** [comment]
It's ok with the commit 
https://github.com/sebdraven/malcom/commit/3992d354f950b6e38aa81cfda77b3b0c85213956
