### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by srilumpa** [tomchop/malcom#40]
Hi,

I have just downloaded malcom to test it but I am unable to launch it simply because: 
1. my database is on another computer than the one I want to run malcom on
2. I have configured authentication on my MongoDB

I see you have created a *db_local* section in the _malcom.conf_ file but, as my comprehension of the code goes, it does not seem to be used when creating the database sessions (at least in the ```Model``` and ```UserManagement``` classes)

Are you working on it (since the *db_local* section exists) or would you prefer a pull request?

**Comment by tomchop** [comment]
I know, I haven't gotten around to implement this yet. A pull request for this feature is more than welcome.
