### ISSUE TITLE
i cant access my home page in malcom

### ISSUE THREAD

**Issue by prabhakaran-s** [tomchop/malcom#49]
hi guys,

i installed malcom using docker. but, i cant access my home page of malcom, it directly going into dataset and in feeds all my running services are in "NO". Please guide me in this.

Thanks in advance.

**Comment by tomchop** [comment]
Which docker image are you pulling? Try pulling `malcom-automatic` instead of just `malcom`.

**Comment by tomchop** [comment]
Any news on this?
