### ISSUE TITLE
Overflow Error while loading a 3.6GB pcap file

### ISSUE THREAD

**Issue by eldraco** [tomchop/malcom#6]
This happen on master (057f471) and dev (311b1e5) branches. 

[DEBUG] - [-] No TLS interception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/handler.py", line 84, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/user/dir/aplics/malcom/Malcom/web/webserver.py", line 76, in malcom_app
    return app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/dir/aplics/malcom/Malcom/web/webserver.py", line 401, in sniffer
    Malcom.sniffer_sessions[session_name].pcap = file.read()
OverflowError: requested number of bytes is more than a Python string can hold
{'CONTENT_LENGTH': '3884500716',
 'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryDuuQMOS7h3fOpAHu',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate,sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,es;q=0.6',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': '192.168.1.20:8080',                                                                                                                                                              
 'HTTP_ORIGIN': 'http://192.168.1.20:8080',                                                                                                                                                     
 'HTTP_REFERER': 'http://192.168.1.20:8080/sniffer/',                                                                                                                                           
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36',                                                                   
 'PATH_INFO': '/sniffer/',                                                                                                                                                                      
 'QUERY_STRING': '',                                                                                                                                                                            
 'REMOTE_ADDR': '192.168.1.20',                                                                                                                                                                 
 'REMOTE_PORT': '48701',                                                                                                                                                                        
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'werkzeug.request': <Request 'http://192.168.1.20:8080/sniffer/' [POST]>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0xb748c0d0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0xa7ed3fac>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with OverflowError

**Comment by tomchop** [comment]
Handling large amounts of data (i.e. flows) will be dealt with in future versions.
